/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 small_and_large_intestine.glb --types 
Author: antonia.sundberg (https://sketchfab.com/antonia.sundberg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/small-and-large-intestine-8a1ca8e3ca224cdeb9264674416bde38
Title: Small and large intestine
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'
import type { ModelProps } from './Brain'

type GLTFResult = GLTF & {
  nodes: {
    Tjocktarm_Default_Material_0: THREE.Mesh
    Tjocktarm_Default_Material_0_1: THREE.Mesh
    Tunntarm_Default_Material_0: THREE.Mesh
  }
  materials: {
    Default_Material: THREE.MeshStandardMaterial
    Default_Material_0: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function Intestine(props: ModelProps) {
  const { nodes, materials } = useGLTF('/small_and_large_intestine.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.037}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[15.286, 3.827, -1.997]} scale={0.1}>
            <mesh geometry={nodes.Tjocktarm_Default_Material_0.geometry} material={materials.Default_Material} />
            <mesh geometry={nodes.Tjocktarm_Default_Material_0_1.geometry} material={materials.Default_Material} />
          </group>
          <mesh geometry={nodes.Tunntarm_Default_Material_0.geometry} material={materials.Default_Material_0} position={[14.166, 10.696, 1.169]} scale={0.1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/small_and_large_intestine.glb')
